### ISSUE TITLE
Container Credential Guard not being invoked with Hyper-V error "The RPC server is unavailable.  (0xC0020017)"

### ISSUE THREAD

**Issue by selzoc** [microsoft/Windows-Containers#221]
**Describe the bug**
Following the instructions laid out at https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/gmsa-run-container, we are unable to create a container when we pass in a credential spec.  To reduce the amount of variables, we are using the [plugin from AKS](https://github.com/microsoft/Azure-Key-Vault-Plugin-gMSA), including their install script.  We have verified that the container host can resolve the DNS of the DC.

When we try to create a container, we observe the following:
```
PS C:\> docker run --security-opt "credentialspec=file://credspec_aks.json" -it mcr.microsoft.com/windows/servercore:ltsc2019 powershell
docker: Error response from daemon: hcsshim::CreateComputeSystem a7d2856c130510cd6216d18bae4c58744b00c3ceec6f35e7d9ae150c8514a4e5: winapi error #3489792023.

PS C:\> Get-WinEvent -LogName Microsoft-Windows-Hyper-V-Compute-Admin -MaxEvents 1 | format-list


TimeCreated  : 5/4/2022 5:36:26 PM
ProviderName : Microsoft-Windows-Hyper-V-Compute
Id           : 11507
Message      : Failed to setup the external credentials for Container
               'a7d2856c130510cd6216d18bae4c58744b00c3ceec6f35e7d9ae150c8514a4e5': The RPC server is unavailable.
               (0xC0020017).

PS C:\> get-winevent -logname Microsoft-Windows-Containers-CCG/Admin
get-winevent : There is not an event log on the localhost computer that matches
"Microsoft-Windows-Containers-CCG/Admin".
At line:1 char:1
+ get-winevent -logname Microsoft-Windows-Containers-CCG/Admin
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft-Windows-Containers-CCG/Admin:String) [Get-WinEvent], Excepti
   on
    + FullyQualifiedErrorId : NoMatchingLogsFound,Microsoft.PowerShell.Commands.GetWinEventCommand
```

**To Reproduce**
1. Create an azure vm from the `Windows Server 2019 Datacenter Server Core with Containers - Gen1` image
2. Copy `CCGAKVPlugin.dll` from an AKS windows node and transfer it to the new vm
3. Run the [install script](https://github.com/microsoft/Azure-Key-Vault-Plugin-gMSA/blob/main/src/CCGAKVPlugin/InstallPlugin.ps1) to register the plugin
4. Place a credential spec referencing the `PluginGUID` of the `CCGAKVPlugin` (`{CCC2A336-D7F3-4818-A213-272B7924213E}`) in `C:\ProgramData\docker\credentialspecs`
1. `docker run --security-opt "credentialspec=file://credspec_aks.json" -it mcr.microsoft.com/windows/servercore:ltsc2019 powershell`
1. `Get-WinEvent -LogName Microsoft-Windows-Hyper-V-Compute-Admin | format-list`
5. `Get-WinEvent -LogName Microsoft-Windows-Containers-CCG/Admin  | format-list`

**Expected behavior**
The docker container should start and a `CCG.exe` instance should also be running.

**Configuration:**
 - Edition: Server 2019 
 - Base Image being used: `2019-Datacenter-Core-with-Containers` (Azure)
 - Container engine: docker
 - Container Engine version: 20.10.9

Interestingly, if we follow the same steps on the `Visual Studio 2019 Community (latest release) on Windows Server 2019 (x64) - Gen1` image from azure, we are able to run a container with a credential spec with no errors.

**Additional context**
Previous issue: https://github.com/microsoft/Windows-Containers/issues/196
(tagging @cwilhit as he was helpful on that one)

Is there missing documentation around how to setup a container host for GMSA/CCG operations?

**Comment by judyliu-ms** [comment]
Hi @selzoc, thank you for sharing! We are investigating this scenario, to help us better identify the issue do you mind running this cmd and sharing the logs: 
`Get-WinEvent -LogName Microsoft-AKSGMSAPlugin/Admin`

**Comment by selzoc** [comment]
Hi @judyliu-ms!

There are no logs, as I don't believe the plugin gets instantiated:

```powershell
PS C:\> Get-WinEvent -LogName Microsoft-AKSGMSAPlugin/Admin
Get-WinEvent : There is not an event log on the localhost computer that matches "Microsoft-AKSGMSAPlugin/Admin".
At line:1 char:1
+ Get-WinEvent -LogName Microsoft-AKSGMSAPlugin/Admin
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft-AKSGMSAPlugin/Admin:String) [Get-WinEvent], Exception
    + FullyQualifiedErrorId : NoMatchingLogsFound,Microsoft.PowerShell.Commands.GetWinEventCommand
```

**Comment by judyliu-ms** [comment]
@selzoc have you imported the manifest to collect the logs? this should be the command: `wevutil im <manifestname.man>`

**Comment by selzoc** [comment]
Where do I get `<manifestname.man>`?  I'm a bit confused.  The only match on `manifest` in the AKS plugin repo is https://github.com/microsoft/Azure-Key-Vault-Plugin-gMSA/blob/main/src/10.0.18362.0/WppConfig/Rev1/manifest.tpl - is that what I'm supposed to use?

As a more general point, we have our own custom plugin that doesn't work in the same way, but I figured I could start with a "known good" plugin for this issue.

**Comment by judyliu-ms** [comment]
This is the manifest (.man) file: https://github.com/microsoft/Azure-Key-Vault-Plugin-gMSA/blob/main/src/CCGAKVPlugin/CCGAKVPluginEvents.man

**Comment by selzoc** [comment]
Wow!  That was a great suggestion.  We were able to determine via those logs that the plugin _was_ indeed getting instantiated, and we needed to have the `PluginInput` in our credential spec in a certain format.  We then applied the same logging technique to our custom plugin, and also saw it succeed!

I think we were thrown off by [these troubleshooting steps](https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/gmsa-troubleshooting#non-domain-joined-container-hosts-use-event-logs-to-identify-configuration-issues), which imply that the `Microsoft-Windows-Containers-CCG/Admin` logs should always be present.  We then assumed that since there were no logs there (for example, we would expect to see the "Container Credential Guard instantiated the plug-in" event) that our plugin wasn't being instantiated.

Can you explain when this log file is created and why it's missing on our Server core machine?

**Comment by selzoc** [comment]
hi @judyliu-ms, any updates here?  Do you know what could cause the `Microsoft-Windows-Containers-CCG/Admin` log not to be populated?  It would be very handy to have that for troubleshooting.

**Comment by judyliu-ms** [comment]
Great question, gathering some logs would help us diagnose why no events appear. Do you mind following these steps: 

1. Open Feedback Hub and create a new feedback item
2. Select the "Security and Privacy" category, and then the “Logging Into Your PC” subcategory.
3. Click "Start recording" and reproduce the issue. Monitoring persists across logon/logoff and reboots.
4. Return to Feedback Hub, click "Stop recording", and submit your feedback. 
5. Click the "Share" button in the top right corner to get a link to the feedback. Send us the link.

**Comment by selzoc** [comment]
Hi @judyliu-ms - can you tell me how to install Feedback Hub on a Windows 2019 Server Core machine?  The only references I see are to Windows 10.  Your instructions also seem oriented toward a machine with a desktop experience.

Thanks!

**Comment by selzoc** [comment]
Hello! Just bumping this since it's been a bit.  Any help getting the `Microsoft-Windows-Containers-CCG/Admin` logs to show up would be appreciated 😅

**Comment by michbern-ms** [comment]
@selzoc - New to the party here, but this caught my attention.  I think the answer to your question is compositional: Server Core does not default to including the feature that provides "Microsoft-Windows-Containers-CCG/Admin".

I poked around a bit, and that log seems to be provided by the feature called "Containers."  i.e., from PowerShell, I did:

`Enable-WindowsOptionalFeature -FeatureName "Containers" -Online -All`

and rebooted the machine.  I then went back to PowerShell and did:

`Get-WinEvent -ListLog *ccg*`

and it reported the CredGuard log as expected:

![image](https://user-images.githubusercontent.com/99994515/190498858-264bc283-e18c-4983-8368-125f8346d6db.png)

So: can you please see if you have the 'Containers' feature installed?  And if not, does installing it give you access to the CredGuard log?

**Comment by selzoc** [comment]
Hi @michbern-ms ! 

Yes, the Containers feature is installed, and I am able to run containers successfully. As mentioned above, the image I'm using is `2019-Datacenter-Core-with-Containers` provided by Azure.

**Comment by michbern-ms** [comment]
@selzoc That was very helpful.  The relevant difference may be Server 2019 vs. Server 2022 -- the CCG log was not present originally in Server 2019, but it was added to it later, so I'm trying to determine whether we expect the CCG log to be present on Server 2019 Azure VM images or not.

**Comment by selzoc** [comment]
@michbern-ms Oh wow, that's awesome knowledge!  Yes, IME it _is_ present in Server images, but not Sever Core.  Would be great to have the CCG logs everywhere as otherwise troubleshooting is basically impossible.

**Comment by selzoc** [comment]
@michbern-ms Is there a plan to add the CCG logs to all Server 2019 images?

**Comment by michbern-ms** [comment]
@selzoc Good timing of your question - I am having exactly this conversation with the Windows Servicing team.   I am helping them understand the impact of the issue on Server 2019.

It's worth noting that the issue does not exist in Server 2022, so when you are ready to move forward to Server 2022, you'll pick up the fix for this.

**Comment by selzoc** [comment]
@michbern-ms Great, I hope the CCG logs get added - without them, the feature is not really useful.  We're in the midst of adding support for CCG to Cloud Foundry and we do not plan on basing any images on Server 2022.

**Comment by selzoc** [comment]
Hi @michbern-ms, any updates here?  Thanks!

**Comment by michbern-ms** [comment]
The issue is understood - it's not as simple as adding the CCG logs.  The neutral binaries are present; it's just the localized .MUI file that is missing, for a complex reason - but one we understand.  I'm working with the team to validate a proposed fix.

**Comment by selzoc** [comment]
Thanks for the update!  Any idea of a timeline?  Is this a file I could add myself at least temporarily to get at least English logs out?

**Comment by michbern-ms** [comment]
WARNING: The following is not a supported solution.  This is just one engineer, talking to another, about a troubleshooting step.

OK, that said, if you have access to a full Server 2019 build, you can look for %SystemRoot%\system32\en-us\ccg.exe.mui.  That's the file that is missing to enable the CCG logs.  If you copy that file to the corresponding location in the container, you should be able to see the problem is resolved.  It would be rather helpful if you could try that and let me know if it worked.

**Comment by selzoc** [comment]
Hi @michbern-ms - no luck unfortunately!

I copied `CCG.exe.mui` to the Server Core container host at `C:\Windows\System32\en-US` and restarted some containers, but I still get
```
> get-winevent -logname Microsoft-Windows-Containers-CCG/Admin
get-winevent : There is not an event log on the localhost computer that matches "Microsoft-Windows-Containers-CCG/Admin".
At line:1 char:1
+ get-winevent -logname Microsoft-Windows-Containers-CCG/Admin
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft-Windows-Containers-CCG/Admin:String) [Get-WinEvent], Exception
    + FullyQualifiedErrorId : NoMatchingLogsFound,Microsoft.PowerShell.Commands.GetWinEventCommand
```

I also attempted to run 
```
New-Eventlog -source Microsoft-Windows-Containers-CCG -LogName Microsoft-Windows-Containers-CCG/Admin -MessageResourceFile "C:\Windows\System32\CCG.exe" -CategoryResourceFile "C:\Windows\System32\CCG.exe"
```
Which does create a log file at `%SystemRoot%\System32\winevt\logs\Microsoft-Windows-Containers-CCG%4Admin.evtx` but it seems like there's still a missing step somewhere, as now I get:
```
> get-winevent -logname Microsoft-Windows-Containers-CCG/Admin
get-winevent : No events were found that match the specified selection criteria.
At line:1 char:1
+ get-winevent -logname Microsoft-Windows-Containers-CCG/Admin
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [Get-WinEvent], Exception
    + FullyQualifiedErrorId : NoMatchingEventsFound,Microsoft.PowerShell.Commands.GetWinEventCommand
```

**Comment by michbern-ms** [comment]
WARNING: The following is not a supported solution. This is just one engineer, talking to another, about a troubleshooting step.

[CCGEvents.man.txt](https://github.com/microsoft/Windows-Containers/files/10027621/CCGEvents.man.txt)

OK, @selzoc , one more try - I replicated your setup exactly and this seemed to work for me.

1. Get the attached file on to the machine
2. Rename it to CCGEvents.man
3. run:
`wevtutil im CCGEvents.man`

I now see:

```
PS C:\Users\LocalAdmin> Get-WinEvent -ListLog *ccg*

LogMode   MaximumSizeInBytes RecordCount LogName
-------   ------------------ ----------- -------
Circular             1052672           0 Microsoft-Windows-Containers-CCG/Admin
```

Your help here is invaluable, since I'd much rather have a confirmed solution before I drive it all the way to completion.
To be clear, this is all on the Container Host, not in the Container itself.

**Comment by selzoc** [comment]
Oh, so close!

Now I'm getting _most_ of the event, but not the `Message` field
```
> get-winevent -logname Microsoft-Windows-Containers-CCG/Admin | format-list

TimeCreated  : 11/17/2022 4:37:09 AM
ProviderName : Microsoft-Windows-Containers-CCG
Id           : 2
Message      :

TimeCreated  : 11/17/2022 4:36:39 AM
ProviderName : Microsoft-Windows-Containers-CCG
Id           : 1
Message      :
```

I tried also copying the `CCG.exe.mui` file and it didn't seem to make a difference.

I know from [this troubleshooting guide](https://learn.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/gmsa-troubleshooting#events-and-descriptions) that the `Message` will contain important information.

**Comment by michbern-ms** [comment]
That's very odd.  I went through the event registration in depth and it looks identical between the failing case and the successful case.  

Chris, feel free to shoot me a mail at michbern@microsoft.com - it might be worth doing this back and forth in mail.

But I had one more idea for you - telling the events manifest system exactly where the message table is:

wevtutil im evtfiles\CCGEvents.man /mf:^%systemroot^%/System32/en-us/CCG.exe.mui

You'll need to put CCG.exe.mui there in that spot.

If there is a simple way to generate CCG events, that would be helpful to me - otherwise, I'm dependent on you trying out these ideas for me.  Which I do appreciate...  :-)

**Comment by selzoc** [comment]
It worked!

The quickest way I know of to generate these logs is to use [these steps](https://learn.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/gmsa-run-container) and simply give a credspec like `{}`.  You should get some sort of error then:
```
> docker run --security-opt "credentialspec=file://empty.json" -it mcr.microsoft.com/windows/server:ltsc2022 powershell
docker: Error response from daemon: hcsshim::CreateComputeSystem e9e38361653dfdf572b35be59cb8ca0e96a8e0a09f19e00e74b7d5864ff79b24: winapi error #3489660941.

> Get-WinEvent -LogName Microsoft-Windows-Containers-CCG/Admin -MaxEvents 1 | Format-List
TimeCreated  : 11/21/2022 5:51:52 PM
ProviderName : Microsoft-Windows-Containers-CCG
Id           : 3
Message      : Container Credential Guard failed to parse the credential spec. Error: An invalid parameter was passed
               to a service or function.
```

**Comment by michbern-ms** [comment]
Thanks, Chris!  I will continue my efforts to get this fix formally backported.

**Comment by michbern-ms** [comment]
We are continuing to make progress on the backporting effort - we are working presently on the safety reviews to make sure that nothing unexpected happens when this change goes out to all of the Server Core images.

**Comment by selzoc** [comment]
Hi @michbern-ms , just checking in - has the backport been released yet?

**Comment by michbern-ms** [comment]
@selzoc Your timing is excellent.  I was waiting for today - the backport fix is in the 3B release which became available at 10:00am today.   I tested the patches a couple of weeks ago and they do make the Microsoft-Windows-Containers-CCG log available on Server Core 2019.   Hopefully you are able to confirm that on your end!

**Comment by selzoc** [comment]
Hi @michbern-ms !

Sorry it took me a bit, but I have verified that the logs are now available without any additional configuration on our images.  Thanks so much for bringing this over the finish line!

**Comment by michbern-ms** [comment]
@selzoc - Hooray!  The end of a long journey.  Have a good weekend!
